# Generated by Django 4.0.5 on 2022-06-13 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='edad',
            field=models.ImageField(upload_to=''),
        ),
    ]
