# Generated by Django 4.0.5 on 2022-06-13 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_familiar_apellido_familiar_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='familiar',
            name='mail',
        ),
    ]
